---
name: Dockle

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  dockle:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTENT_TRUST: 1
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v0.4.14/dockle_0.4.14_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
      - run: |
          cp .config/docker_example.env .config/docker.env
          cp ./docker-compose_example.yml ./docker-compose.yml
      - run: |
          docker compose up -d web
          echo "----------------"
          docker compose images web | cat
          echo "----------------"
          IMAGE_ID="$(docker compose images web | awk 'OFS=":" {print $4}' | tail -n +2)"
          echo "IMAGE_ID: $IMAGE_ID"
          docker tag "$IMAGE_ID" misskey-web:latest
      - run: |
          cmd="dockle --exit-code 1 misskey-web:latest ${image_name}"
          echo "> ${cmd}"
          eval "${cmd}"
